FROM node:10.16.3-alpine

#Create app directory and use it as the working directory

RUN mkdir -p /srv/app/client
WORKDIR /srv/app/client

#to copy the go directory to /usr/local use : COPY go /usr/local/go

COPY ./client/package.json /srv/app/client/client/
COPY ./client/package-lock.json /srv/app/client/client/
WORKDIR /srv/app/client/client
RUN npm install


WORKDIR /srv/app/client
COPY ./client/public /srv/app/client/client/public/
COPY ./client/src /srv/app/client/client/src/
COPY ./handlers /srv/app/client/handlers/
COPY ./models /srv/app/client/models/
COPY ./routes /srv/app/client/routes/


WORKDIR /srv/app/client/client

CMD ["npm" , "start"]
