FROM node:10.16.3-alpine

#Create app directory and use it as the working directory

RUN mkdir -p /srv/app/server
WORKDIR /srv/app/server

#to copy the go directory to /usr/local use : COPY go /usr/local/go

COPY ./package.json /srv/app/server/
COPY ./package-lock.json /srv/app/server/
RUN npm install


COPY ./app.js /srv/app/server/
COPY ./handlers /srv/app/server/handlers/
COPY ./models /srv/app/server/models/
COPY ./routes /srv/app/server/routes/

CMD ["npm" , "start"]
